version: '3.7'
services:
  kong:
    image: kong:3.6
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
    volumes:
      - ./01-introduction-to-kong/kong.yaml:/usr/local/kong/declarative/kong.yaml
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: ./backend-services
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    command: node service-1/service1.js

  server2:
    build:
      context: ./backend-services
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    command: node service-2/service2.js